name: harmonisation_env
channels:
- conda-forge
dependencies:
- fsspec
- jupyterlab
- langchain
- numpy
- openai
- openpyxl
- pandas
- pdfminer.six
- python-dotenv
- python-duckdb
- scipy
- streamlit
- tiktoken
- pip